CREATE TABLE Users (
	UID INT NOT NULL AUTO_INCREMENT,
	UserName VARBINARY(50),
	Password VARBINARY(50),
	Salt VARBINARY(50),
	UIID INT NOT NULL,
	CONSTRAINT Users_UID_PK PRIMARY KEY (UID),
	CONSTRAINT Users_UIID_FK FOREIGN KEY (UIID)
	REFERENCES UserImages (UIID)
) Engine = InnoDB CHARACTER SET = utf8 COLLATE = utf8_bin;

DROP TABLE Users;

CREATE TABLE UserImages (
	UIID INT NOT NULL AUTO_INCREMENT,
	Type VARCHAR (255) NOT NULL,
	Image MEDIUMBLOB NOT NULL,
	CONSTRAINT UserImages_UIID_PK PRIMARY KEY (UIID)
) Engine = InnoDB CHARACTER SET = utf8 COLLATE = utf8_bin;

DROP TABLE UserImages;

CREATE TABLE HasTeamMember (
	UID INT NOT NULL,
	PKID INT NOT NULL,
	TeamOrder INT NOT NULL,
	CONSTRAINT HasTeamMember_PK PRIMARY KEY (UID, PKID),
	CONSTRAINT HasTeamMember_UID_FK FOREIGN KEY (UID)
	REFERENCES Users (UID) ON DELETE CASCADE,
	CONSTRAINT HasTeamMember_PKID_FK FOREIGN KEY (PKID)
	REFERENCES Pokemon (PKID) ON DELETE CASCADE
) Engine = InnoDB CHARACTER SET = utf8 COLLATE = utf8_bin;

DROP TABLE HasTeamMember;

CREATE TABLE HasFavorite (
	UID INT NOT NULL,
	PKID INT NOT NULL,
	CONSTRAINT HasFavorite_PK PRIMARY KEY (UID, PKID),
	CONSTRAINT HasFavorite_UID_FK FOREIGN KEY (UID)
	REFERENCES Users (UID) ON DELETE CASCADE,
	CONSTRAINT HasFavorite_PKID_FK FOREIGN KEY (PKID)
	REFERENCES Pokemon (PKID) ON DELETE CASCADE
) Engine = InnoDB CHARACTER SET = utf8 COLLATE = utf8_bin;

DROP TABLE HasFavorite;

CREATE TABLE Evolutions (
	EvolvesTo INT NOT NULL,
	EvolvesFrom INT NOT NULL,
	CONSTRAINT Evolutions_PK PRIMARY KEY (EvolvesTo, EvolvesFrom),
	CONSTRAINT Evolutions_EvolvesTo_FK FOREIGN KEY (EvolvesTo)
	REFERENCES Pokemon (PKID),
	CONSTRAINT Evolutions_EvolvesFrom_FK FOREIGN KEY (EvolvesFrom)
	REFERENCES Pokemon (PKID)
) Engine = InnoDB CHARACTER SET = utf8 COLLATE = utf8_bin;

DROP TABLE Evolutions;

CREATE TABLE Pokemon (
	PKID INT NOT NULL AUTO_INCREMENT,
	DexNumber INT NOT NULL,
	Name VARCHAR(50),
	IID INT NOT NULL,
	SID INT NOT NULL,
	CONSTRAINT Pokemon_PKID_PK PRIMARY KEY (PKID),
	CONSTRAINT Pokemon_IID_FK FOREIGN KEY (IID)
	REFERENCES PokemonImages (IID), 
	CONSTRAINT Pokeomon_SID_FK FOREIGN KEY (SID)
	REFERENCES PokemonSprites (SID)
) Engine = InnoDB CHARACTER SET = utf8 COLLATE = utf8_bin;

DROP TABLE Pokemon;

CREATE TABLE PokemonImages (
	IID INT NOT NULL AUTO_INCREMENT,
	Type VARCHAR(50),
	Image MEDIUMBLOB NOT NULL,
	CONSTRAINT PokemonImages_IID_PK PRIMARY KEY (IID)
) Engine = InnoDB CHARACTER SET = utf8 COLLATE = utf8_bin;

DROP TABLE PokemonImages;

CREATE TABLE PokemonSprites (
	SID INT NOT NULL AUTO_INCREMENT,
	Type VARCHAR(50),
	Image MEDIUMBLOB NOT NULL,
	CONSTRAINT PokemonSprites_SID_PK PRIMARY KEY (SID)
) Engine = InnoDB CHARACTER SET = utf8 COLLATE = utf8_bin;

DROP TABLE PokemonSprites;


